JSON
sad-company/sad-forms-backend pull request #15
Opened 2023-06-25 09:37 UTC by Serg-Bartosh

I know that the sandbox does not apply to JSON, but I was too lazy to make a new branch

2023-06-27 10:09 UTC, s373r requested changes

2023-06-27 10:09 UTC, s373r commented on forms/views.py
> +        schema = json.load(text)
можно просто `return json.load(raw_json_schema)` (или назвать переменную `json_schema_as_str` или `schema_as_str`), выбирай любой более конкртеный вариант

2023-06-27 10:09 UTC, s373r commented on forms/views.py
> +def loader_jsonschema():
название не отражает сути -- что мы делаем? мы загружаем джейсон схему. какую джейсон схему? джейсон схему создания формы. проверяем ли мы все приходящие данные? нет, только `questions` поле

соединяем всё в название

1) мы загружаем джейсон схему  -- `def load_` + (слово `jsonschema` вставим в конце ради правил англ)
2) джейсон схему создания формы -- + `form_create_` +
3) только `questions` поле -- + `questions_jsonschema()`


итог: `def load_form_create_questions_jsonschema()`

2023-06-27 10:09 UTC, s373r commented on forms/views.py
> +    with open('/home/onehayzent/src/django/sad-forms-backend/forms/json_schema.json', 'r') as text:
файл слишком общее имеет название. предлагаю более конкретное + отдельную папку, т.к. не факт что это единственная json schema

`sad-forms-backend/forms/json_schemas/form_create_questions.json`

2023-06-27 13:46 UTC, Serg-Bartosh commented on forms/views.py
> +            schema = loader_jsonschema()
угу, тоже про это думал, дякякую за комент

2023-06-27 13:48 UTC, Serg-Bartosh commented on forms/views.py
> +def loader_jsonschema():
Как всегда гениально

2023-06-27 14:56 UTC, Serg-Bartosh commented on forms/views.py
> +                Form.objects.create(**data.cleaned_data)
1) Eсли "это" - 24 строка , то да 
2) У нас не может "не получится сохранить запись", для того что бы это не произошло у нас есть проверка на 19 строке и 23, если хоть одна из них не проходит то будет HttpResponse 500 

@s373r

2023-06-27 15:00 UTC, Serg-Bartosh commented on forms/views.py
> +            schema = loader_jsonschema()
Сделано!

2023-06-27 15:06 UTC, Serg-Bartosh commented on forms/views.py
> +    with open('/home/onehayzent/src/django/sad-forms-backend/forms/json_schema.json', 'r') as text:
Готово!

2023-06-27 15:07 UTC, Serg-Bartosh commented on forms/views.py
> +        schema = json.load(text)
Сделано!

2023-06-27 15:07 UTC, Serg-Bartosh commented on forms/views.py
> +def loader_jsonschema():
Сделано!

2023-07-11 10:07 UTC, s373r requested changes

2023-07-11 10:07 UTC, s373r commented on forms/views.py
> +            questions = json.loads(request.POST['questions'])
@Serg-Bartosh , не вижу изменений :(

Всё равно думаю, что это лишний код:
```py
questions = request.POST['questions']
```

Попробуй передавать в ...

```py
validate(instance=questions, schema=FORM_CREATE_QUESTIONS_JSONSCHEMA)
```

... `data.questions` или `data.cleaned_data.questions` (пишу предположительно, нужно проверять)

2023-08-10 16:20 UTC, s373r requested changes

2023-08-10 16:20 UTC, s373r commented on forms/views.py
> +                validate(instance=data.cleaned_data['questions'], schema=FORM_CREATE_QUESTIONS_JSONSCHEMA)
Эта валидация не должна быть внутри блока `try/except`, в котором ты отлавливаешь ошибки по базе данных (т.к. это отдельное действие)

Действия:
1) нужно вынести в из этого блока `try/expect`
2) тут у нас образовывается спагетти-код (гугли термин), т.к. вложенность какая-то дополнительная, поэтому, чтобы убрать один блок вложенности (сдвига вправо), советую следующее (методика называется early return):

```py
...
if request.method == "POST":
    form_create_dto = FormCreateDto(request.POST)

    if not form_create_dto.is_valid():
        return HttpResponseBadRequest("Form is not valid!") # используем класс наследник от `HttpResponse`, который уже содержит в себе статус код

    questions = form_create_dto.cleaned_data.questions
    validate(instance=questions, schema=FORM_CREATE_QUESTIONS_JSONSCHEMA)

    # with atomic(): -- не нужен, мы создаём только один объект, поэтому нам транзакия не нужна
    try:
      Form.objects.create(**data.cleaned_data)
    except DatabaseError as e:
      return HttpResponseServerError(e)
    
    return HttpResponse() # 200 не нужно передавать
...
```

2023-08-10 16:20 UTC, s373r commented on forms/views.py
> +                validate(instance=data.cleaned_data['questions'], schema=FORM_CREATE_QUESTIONS_JSONSCHEMA)
(сделай изменения отдельным коммитом!)

2023-08-10 16:21 UTC, s373r commented on forms/views.py
> +                Form.objects.create(**data.cleaned_data)
В процессе, пока не закрываю

2023-08-16 08:25 UTC, s373r approved these changes

2023-08-16 08:25 UTC, merged