🗃️ Moving project to new database
sad-company/sad-forms-backend pull request #19
Opened 2023-09-02 16:20 UTC by Serg-Bartosh

2023-09-02 16:41 UTC, s373r requested changes

2023-09-02 16:41 UTC, s373r commented on sad_forms/settings.py
> +        'PORT': '5433',
Мы должны исправить этот хардкод, на считывание данных из окружения

2023-09-02 17:06 UTC, s373r commented on sad_forms/settings.py
> +        'PORT': '5433',
Наша цель: заменить эти хардкод значения из на данные из переменных окружения

Вот статья, в которой описано, что нам нужно:
https://dev.to/earthcomfy/django-how-to-keep-secrets-safe-with-python-dotenv-5811

Переменные окружения, которые будут у нас:
```
        'DB_HOST'
        'DB_PORT'
        'DB_NAME'
        'DB_USER'
        'DB_PASSWORD'
```

Твоя цель:
1) добавить новый пакет
2) загрузить переменные окружения в settings.py
3) считать значения данных подключения (см названия выше)
4) чтобы каждый раз не задавать переменные окружения, создай файл `.env`, в который запиши в формате ...

```
KEY1=VALUE1
KEY2=VALUE2
...
```

... значения переменных окружения.

5) файл должен быть в гит игноре, т.к. это файл исключительно для упрощения разработки -- на проде, данные будут считываться из окружения

2023-09-03 07:03 UTC, s373r requested changes

2023-09-03 07:03 UTC, s373r commented on sad_forms/settings.py
Добавь файл .env.example, который будет служить для простоты создания и заполнения .env

Его содержание будет следующим:

DB_HOST=host
DB_PORT=5432
DB_NAME=name
DB_USER=user
DB_PASSWORD=password

2023-09-03 09:19 UTC, Serg-Bartosh commented on sad_forms/settings.py
> +        'PORT': '5433',
done

2023-09-03 09:19 UTC, Serg-Bartosh commented on sad_forms/settings.py
> +load_dotenv()
Ок, но хочу обьяснения почему нельзя это оставить в блоке "Database", для лучшей читаимости

2023-09-03 09:26 UTC, Serg-Bartosh commented on sad_forms/settings.py
=Done

2023-09-03 09:34 UTC, Serg-Bartosh commented on sad_forms/settings.py
> +        'PORT': getenv('DB_PORT'),
:Done

2023-09-03 09:34 UTC, Serg-Bartosh commented on sad_forms/settings.py
> +load_dotenv()
xDone

2023-09-03 10:55 UTC, s373r requested changes

2023-09-03 10:55 UTC, s373r commented on sad_forms/settings.py
Не сделано

2023-09-03 10:55 UTC, s373r commented on sad_forms/settings.py
> +        'PASSWORD': getenv('DB_PASSWORD')
**Необязательное изменение:**

коммит называется ...
🚧 Logical sort 
... что является не конкретным называнием. простое проверочное действие для имени коммита это -- посмотреть на название коммита и попытаться понять, какое место в коде он правит

в этом случае, мы смотрим на название и хочется спросить: логическая сортировка чего? где?

Предлагаемое название:
♻️ Reorder DB keys settings
(это изменение как минимум рефакторинг, а не работа в процессе)

2023-09-03 12:03 UTC, Serg-Bartosh commented on sad_forms/settings.py
done

2023-09-03 12:08 UTC, s373r approved these changes

2023-09-03 12:08 UTC, merged