Environment variables
sad-company/sad-forms-backend pull request #20
Opened 2023-09-27 18:40 UTC by Serg-Bartosh

2023-09-28 17:07 UTC, s373r requested changes

2023-09-28 17:07 UTC, s373r commented on sad_forms/settings.py
> +def validator_environment_variables(environment_variables: {}) -> None:
1) исправь дикие отступы внутри функции
2) название не подходит, предложи варианты
3) тип `environment_variables`, выставь хотя бы в `dict[str, str]`
4) загружай схему внутри этой функции, глобальная переменная на настройки не нужна, она используется только один раз и в одном месте

2023-09-28 17:07 UTC, s373r commented on sad_forms/settings.py
> +def load_form_validation_environment_variables():
1) название функции -- ты не загружаешь "переменные окружения валидации формы", а "загружаешь схему валидации переменных окружения"
2) отсутствует тип возвращаемого значения

2023-09-28 17:41 UTC, Serg-Bartosh commented on sad_forms/settings.py
>  ]
Я подумал это смещение комитов , с не табуляция

2023-09-28 19:38 UTC, Serg-Bartosh commented on sad_forms/settings.py
> +		print(f"Данные в .env были введены не правильно, ошибка подключения к БД \n {e}")
1) Data in .env was entered incorrectly
2) Error validating data from .env

2023-09-28 19:55 UTC, alena-bartosh commented on sad_forms/unit_tests/validator_environment_variables.py
> +			self.assertRaises(ValidationError)
1. Круто, что ты начал писать тесты
2. В чём смысл этого теста?

2023-09-28 19:56 UTC, alena-bartosh commented on sad_forms/unit_tests/validator_environment_variables.py
> +		               'DB_USER': 'adsad', 'DB_PASSWORD': 'AAAAAA'}
```DB_PORT': 'asdsad'``` - это валидное значение порта?

2023-09-28 19:58 UTC, alena-bartosh commented on sad_forms/unit_tests/validator_environment_variables.py
> +			self.assertRaises(ValidationError)
2. Я поняла, в чём смысл. Нужно им имена поменять по-хорошему. Потому что называются ```_valid_environment_variables(self):```, а по сути тестируешь разные не валидные значения

2023-09-28 19:59 UTC, alena-bartosh commented on sad_forms/unit_tests/validator_environment_variables.py
> +			self.assertRaises(ValidationError)
Например, ```test_when_host_non_valid_(self):```. В тестах часто применяют слово ```when```

2023-09-28 20:00 UTC, alena-bartosh commented on sad_forms/unit_tests/validator_environment_variables.py
> +	def test4_valid_environment_variables(self):
Потому что потом тесты могут удаляться и переписываться, а нумерация это как хардкод. Вот ты удалишь тест_4 и будешь все переименовывать?

2023-09-28 20:02 UTC, alena-bartosh commented on sad_forms/unit_tests/validator_environment_variables.py
> +	def test5_valid_environment_variables(self):
```suggestion
	def test_when_valid_envs(self):
```

2023-10-03 09:40 UTC, s373r commented on sad_forms/unit_tests/validator_environment_variables.py
> +		               'DB_USER': 'adsad', 'DB_PASSWORD': 'AAAAAA'}
нет

2023-10-03 09:41 UTC, s373r commented on sad_forms/unit_tests/validator_environment_variables.py
> +	def test4_valid_environment_variables(self):
@alena-bartosh , шикарный аргумент

2023-10-03 19:09 UTC, Serg-Bartosh commented on forms/views.py
1

2023-10-03 19:12 UTC, Serg-Bartosh commented on sad_forms/settings.py
>  ]
Done

2023-10-03 19:24 UTC, Serg-Bartosh commented on forms/views.py
> +    with open('json_schemas/form_create_questions.json', 'r') as raw_json_schema:
Reverted

2023-10-03 19:53 UTC, Serg-Bartosh commented on json_schemas/validation_of_environment_variables.json
> +      "minimum": 4,
Done

2023-10-03 19:53 UTC, Serg-Bartosh commented on json_schemas/validation_of_environment_variables.json
> +      "pattern": "^[0-9]{4}$"
Done

2023-10-04 15:58 UTC, Serg-Bartosh commented on json_schemas/validation_of_environment_variables.json
> +      "pattern": "^[0-9]{3}\\.[0-9]{1,3}\\.[0-9]\\.[0-9]$"
Done

2023-10-04 15:59 UTC, Serg-Bartosh commented on sad_forms/settings.py
> +		print(f"Данные в .env были введены не правильно, ошибка подключения к БД \n {e}")
Done

2023-10-04 15:59 UTC, Serg-Bartosh commented on sad_forms/settings.py
> +def validator_environment_variables(environment_variables: {}) -> None:
Done

2023-10-04 16:03 UTC, Serg-Bartosh commented on json_schemas/validation_of_environment_variables.json
> +{
Done

2023-10-04 16:04 UTC, Serg-Bartosh commented on sad_forms/unit_tests/validator_environment_variables.py
> +		               'DB_USER': 'adsad', 'DB_PASSWORD': 'AAAAAA'}
Done

2023-10-04 16:04 UTC, Serg-Bartosh commented on sad_forms/unit_tests/validator_environment_variables.py
> +	def test4_valid_environment_variables(self):
Done

2023-10-06 10:19 UTC, s373r requested changes

2023-10-06 10:19 UTC, s373r commented on sad_forms/unit_tests/validator_environment_variables.py
> +            self.assertRaises(ValidationError)
нужно сравнивать еще сообщения ошибок, чтобы они были такие, какими мы их ожидаем

2023-10-06 10:19 UTC, s373r commented on sad_forms/unit_tests/validator_environment_variables.py
> +            self.assertRaises(ValidationError)
нужно сравнивать еще сообщения ошибок, чтобы они были такие, какими мы их ожидаем

2023-10-06 10:19 UTC, s373r commented on sad_forms/unit_tests/validator_environment_variables.py
> +            self.assertRaises(ValidationError)
нужно сравнивать еще сообщения ошибок, чтобы они были такие, какими мы их ожидаем

2023-10-06 10:19 UTC, s373r commented on sad_forms/unit_tests/validator_environment_variables.py
> +            self.assertRaises(ValidationError)
нужно сравнивать еще сообщения ошибок, чтобы они были такие, какими мы их ожидаем

2023-10-06 10:19 UTC, s373r commented on sad_forms/unit_tests/validator_environment_variables.py
> +            self.assertRaises(ValidationError)
нужно сравнивать еще сообщения ошибок, чтобы они были такие, какими мы их ожидаем

2023-10-06 10:19 UTC, s373r commented on sad_forms/unit_tests/validator_environment_variables.py
> +        environment = {'DB_HOST': '128.0.0.1', 'DB_PORT': 5238, 'DB_NAME': 'postgres',
Тогда уж 127.0.0.1

2023-10-06 10:19 UTC, s373r commented on sad_forms/unit_tests/validator_environment_variables.py
> +    def test_when_everything_is_empty(self):
Бессмысленный тест, можно удалить

2023-10-06 10:19 UTC, s373r commented on sad_forms/unit_tests/validator_environment_variables.py
> +    def test_when_all_letters(self):
Бессмысленный тест, можно удалить

2023-10-09 10:15 UTC, Serg-Bartosh commented on sad_forms/unit_tests/validator_environment_variables.py
> +            self.assertRaises(ValidationError)
Done

2023-10-09 10:15 UTC, Serg-Bartosh commented on sad_forms/unit_tests/validator_environment_variables.py
> +            self.assertRaises(ValidationError)
Done

2023-10-09 10:15 UTC, Serg-Bartosh commented on sad_forms/unit_tests/validator_environment_variables.py
> +            self.assertRaises(ValidationError)
Done

2023-10-09 10:15 UTC, Serg-Bartosh commented on sad_forms/unit_tests/validator_environment_variables.py
> +            self.assertRaises(ValidationError)
Done

2023-10-09 10:15 UTC, Serg-Bartosh commented on sad_forms/unit_tests/validator_environment_variables.py
> +            self.assertRaises(ValidationError)
Done

2023-10-09 10:15 UTC, Serg-Bartosh commented on sad_forms/unit_tests/validator_environment_variables.py
> +        environment = {'DB_HOST': '128.0.0.1', 'DB_PORT': 5238, 'DB_NAME': 'postgres',
Done

2023-10-09 10:16 UTC, Serg-Bartosh commented on sad_forms/unit_tests/validator_environment_variables.py
> +    def test_when_everything_is_empty(self):
Done

2023-10-09 10:16 UTC, Serg-Bartosh commented on sad_forms/unit_tests/validator_environment_variables.py
> +    def test_when_all_letters(self):
Done

2023-10-09 12:58 UTC, s373r commented on sad_forms/unit_tests/validator_environment_variables.py
> +            self.assertRaises(ValidationError)
текст ошибок не сравнивается!

2023-10-09 12:58 UTC, s373r commented on sad_forms/unit_tests/validator_environment_variables.py
> +    def test_when_all_letters(self):
текст ошибок не сравнивается!

2023-10-09 13:01 UTC, s373r requested changes

2023-10-09 13:01 UTC, s373r commented on sad_forms/common/env_validator.py
> +            logging.error(f"Environment variable validation error:\n{e}")
покажи (скриншот), как выводится это сообщение в терминале

2023-10-10 09:08 UTC, s373r approved these changes

2023-10-10 09:09 UTC, merged