Create an endpoint to refer to a specific form
sad-company/sad-forms-backend pull request #8
Opened 2023-03-22 08:05 UTC by Serg-Bartosh

2023-03-22 09:42 UTC, s373r requested changes

2023-03-22 09:42 UTC, s373r commented on forms/views.py
> -from django.http import HttpRequest, HttpResponse, HttpResponseNotAllowed, JsonResponse
squash your 2 commits into 1

2023-03-22 09:42 UTC, s373r commented on forms/views.py
> +def show_form_id(request: HttpRequest, form_id: str) -> HttpResponse:
rename `show_form_id()` -> `form_view_by_form_id()`

2023-03-22 21:06 UTC, Serg-Bartosh commented on forms/views.py
> +        return JsonResponse(forms_json, safe=False)
[{'id': 1, 'name': 'test', 'description': '', 'questions': 'Do u like green', 'form_id': 'asdfghjkl;'}]

2023-03-23 09:24 UTC, Serg-Bartosh commented on forms/views.py
> -from django.http import HttpRequest, HttpResponse, HttpResponseNotAllowed, JsonResponse
Done

2023-03-23 09:24 UTC, Serg-Bartosh commented on forms/views.py
> +def show_form_id(request: HttpRequest, form_id: str) -> HttpResponse:
DONE

2023-03-23 09:24 UTC, Serg-Bartosh commented on forms/views.py
> +        return JsonResponse(forms_json, safe=False)
DONE

2023-03-23 10:05 UTC, s373r approved these changes
awesome!

2023-03-23 10:05 UTC, merged